apiVersion: v1
kind: Secret
metadata:
    namespace: to-do-project
    name: postgres-secret-config
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:wisRyxadW1wsFlJk,iv:pIFcFlt9mFy+DS5uFntf5nAWz+OsJNdc+6G2NVcC5Rg=,tag:9wbUm98SiQ5RNFvRzYWkaw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:BoinIOxUGhQ00Pb8,iv:PET07Qn4z8zEintrKBGSFj7WeS6/3N4MtcqoBujf2w0=,tag:92lHjN8MFNfUJPWGw5sEgA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UP1JvOMdtgRDxt3TSChbfPUJ1gc74pvlinsemQ==,iv:vtQRHJGT/Ae49KlqKbtqgHskrWL61SAFARJCQC0UATE=,tag:4Pct790cDDz3lSqshlRqwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rf6mvs2deuyrv34qsl5ftq7tfvs8f9f3d5f4y63hjcpgznyuc42qj6ep8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcnB5czdrOVZxMnhYS3NK
            NlNBUGVCRUtVTjg4aXgwYktqSUY2Rm51Y1JrCmI0c3FTVGJvbTFMNXpjQk1kUGFt
            UDhWY1hEZ1I0c1hTRE5pTFFHUFlxWGsKLS0tIHBVdWpqeFlEbkduRDQxSTRTUUcr
            Z2gvcktiZGJXOTRseWlrNm1SUVJhaVUKHylArvZKV+VQMI+4rBOyZV9DNL7oXV0/
            H4l/qQtCBIwsw/0jqL+ms8ScWDc4Ex1zOSBYNrFuXwmY5RMmZNLojg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-15T13:06:05Z"
    mac: ENC[AES256_GCM,data:4CnQA2h0odMU6spuSRpfwn2Ra4FFtQO9rQdlHc0q/bjvYyweESxvv2esp8kWnt9jQUw04jbPzx5Hx9iyqbRcmfHTaNLgHnhHuOF/N/1VS02nWiVmM8z3TQjRcXOkOcGdWchImxodcr2P9kEoGMJx+1h16pf+39g7Lq6Ih9yj6dM=,iv:P2Hta6MUjC4KRBQPSlMw4Pqk7TiW9ZwlPvO6mpDHux4=,tag:/E8UL6l/oAlfk5knfR5m3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
